logging:
  level:
    dev: info
    org:
      springframework:
        web: ERROR
server:
  port: 8081
  tomcat:
    threads:
      max: 500
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
#  data:
#    redis:
#      repositories:
#        enabled: false
#  redis:
#    jedis:
#      pool:
#        max-active: 16 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 16 # 连接池中的最大空闲连接
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 0 # 连接池中的最小空闲连接
#    host: tendisplus
#    port: 6379
  mvc:
    throw-exception-if-no-handler-found: true
#  cache:
#    caffeine:
#      spec: maximumSize=1024,expireAfterAccess=1800s
#    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


milvus:
  host: milvus
  port: 19530

TFServingServer: tf-serving:8501

clip:
  preprocess:
    commend: python3 /home/PIC/dclip_image_preprocess.py
